import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "MyPortfolio_syedsaadaliaskari",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased bg-[#020617]`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
// Card/Nav Background: #1e1b4b (Deep Indigo)

// Primary Accent: #8b5cf6 (Violet 500)

// Highlight: #f472b6 (Pink 400 - for small icons)
