import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/app/components/Navbar";
import { Home } from "@/app/components/Home";
import { Toaster } from "@/components/ui/sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "MyPortfolio_syedsaadaliaskari",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} antialiased scroll-smooth`}
    >
      <body className="bg-[#020617] text-white min-h-screen flex flex-col">
        <Navbar />
        <main className="flex grow">
          {children}
          <Toaster position="top-center" richColors />
        </main>
      </body>
    </html>
  );
}
// Card/Nav Background: #1e1b4b (Deep Indigo)

// Primary Accent: #8b5cf6 (Violet 500)

// Highlight: #f472b6 (Pink 400 - for small icons)
